apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tutorial-pipeline
spec:
  resources:
  - name: source-repo
    type: git
  - name: web-image
    type: image
  tasks:
  - name: build-skaffold-web
    taskRef:
      name: build-docker-image-from-git-source
    params:
    - name: skaffoldYAMLDir
      value: /workspace/docker-source/ # {"$kpt-set":"skaffoldYAMLDir"}
    resources:
      inputs:
      - name: docker-source
        resource: source-repo
      outputs:
      - name: builtImage
        resource: web-image
